### PR TITLE
update processing

### PR DESCRIPTION
**Pull request by macky4546**
updated coke processing spot to coke lab with default IPL - added teleports into small resources
shorter picking times

### CODE REVIEW

**Comment by GhzGarage** [comment]
I only see code changing the random length of time the bar runs

**Comment by BerkieBb** [comment]
@macky4546 Do you want to update this pull request or can we close this?

**Comment by macky4546** [comment]
I found the ymap and as long as you have that, the original qb-coke will work. we are not pushing maps though
My changes were using the default cokelab IPL.

**Comment by BerkieBb** [comment]
You only changed the processing time, none of your other changes went through

**Comment by GhzGarage** [comment]
@macky4546 Could you do the rest please

**Comment by macky4546** [comment]
Teleports got added into qb-smallresources

**Pull request closed without merging**
